/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Center, useGLTF } from '@react-three/drei';

export default function Laocoon(props) {
	const { nodes, materials } = useGLTF('./laocoon_and_his_sons2.glb');
	return (
		<group
			// rotation={[0, Math.PI / 4, 0]}
			scale={0.25}
			{...props}
			dispose={null}
		>
			<mesh
				geometry={nodes.Object_2.geometry}
				material={materials.None}
				position={[-0.348, -13.822, 14.17]}
				rotation={[-Math.PI, Math.PI / 2, 0]}
			/>
		</group>
	);
}

useGLTF.preload('./laocoon_and_his_sons2.glb');
