/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Center, useGLTF } from '@react-three/drei';

export default function Laocoon(props) {
	const { nodes, materials } = useGLTF('./laocoon-compressed.glb');
	return (
		<Center
			scale={0.25}
			{...props}
			dispose={null}
		>
			<mesh
				geometry={nodes.Object_2.geometry}
				material={materials.None}
				rotation={[-Math.PI, Math.PI / 2, 0]}
			/>
		</Center>
	);
}

useGLTF.preload('./laocoon-compressed.glb');
